INSERT INTO estado VALUES(11,'Rondônia','RO');
INSERT INTO estado VALUES(12,'Acre','AC');
INSERT INTO estado VALUES(13,'Amazonas','AM');
INSERT INTO estado VALUES(14,'Roraima','RR');
INSERT INTO estado VALUES(15,'Pará','PA');
INSERT INTO estado VALUES(16,'Amapá','AP');
INSERT INTO estado VALUES(17,'Tocantins','TO');
INSERT INTO estado VALUES(21,'Maranhão','MA');
INSERT INTO estado VALUES(22,'Piauí','PI');
INSERT INTO estado VALUES(23,'Ceará','CE');
INSERT INTO estado VALUES(24,'Rio Grande do Norte','RN');
INSERT INTO estado VALUES(25,'Paraíba','PB');
INSERT INTO estado VALUES(26,'Pernambuco','PE');
INSERT INTO estado VALUES(27,'Alagoas','AL');
INSERT INTO estado VALUES(28,'Sergipe','SE');
INSERT INTO estado VALUES(29,'Bahia','BA');
INSERT INTO estado VALUES(31,'Minas Gerais','MG');
INSERT INTO estado VALUES(32,'Espírito Santo','ES');
INSERT INTO estado VALUES(33,'Rio de Janeiro','RJ');
INSERT INTO estado VALUES(35,'São Paulo','SP');
INSERT INTO estado VALUES(41,'Paraná','PR');
INSERT INTO estado VALUES(42,'Santa Catarina','SC');
INSERT INTO estado VALUES(43,'Rio Grande do Sul','RS');
INSERT INTO estado VALUES(50,'Mato Grosso do Sul','MS');
INSERT INTO estado VALUES(51,'Mato Grosso','MT');
INSERT INTO estado VALUES(52,'Goiás','GO');
INSERT INTO estado VALUES(53,'Distrito Federal','DF');